name: Clone and Package edk2

on:
  workflow_dispatch:

jobs:
  package-edk2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone edk2 repository
        run: |
          git clone https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init --recursive

      - name: Compress edk2 directory
        run: |
          tar -czf edk2.tar.gz edk2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edk2-archive
          path: edk2.tar.gz
