name: EDK2 Repository Packager

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  package-edk2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4  # 检出当前仓库（空仓库也需要此步骤）

      - name: Clone EDK2 Repository
        run: |
          git clone --depth 1 --progress https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init --recursive

      - name: Zip EDK2 Repository
        run: |
          zip -r edk2-with-submodules.zip edk2/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edk2-full
          path: edk2-with-submodules.zip
